#!/bin/bash
w=$1
word=$2
if [[ $w = '-l' ]];
then
    lc(){
        case "$1" in
               [A-Z])
               n=$(printf "%d" "'$1")
               n=$((n+32))
               printf \\$(printf "%o" "$n")
               ;;
               *)
               printf "%s" "$1"
               ;;
               esac
         }


         for((i=0;i<${#word};i++))
         do
            ch="${word:$i:1}"
            lc "$ch"
         done
echo ""

fi


if [[ $w = '-u' ]];
then
    lc(){
        case "$1" in
               [a-z])
               n=$(printf "%d" "'$1")
               n=$((n-32))
               printf \\$(printf "%o" "$n")
               ;;
               *)
               printf "%s" "$1"
               ;;
               esac
         }


         for((i=0;i<${#word};i++))
         do
            ch="${word:$i:1}"
            lc "$ch"
         done
echo ""
fi
